steps:
  - name: Run Dastardly Action Step
    continue-on-error: true                       
    uses: PortSwigger/dastardly-github-action@main
    with:
      target-url: 'https://ginandjuice.shop'
